// Blind scoring, enforced rather than promised — CLAUDE.md §8.
//
//   node tools/blind.js --sets RECK-default,RECK-allflags,RECK-reference
//   node tools/blind.js --reveal
//
// §8 asks for the reference and AEON to be "scored both blind". That has never
// happened, and the reason is banal: blinding yourself is not something you can
// decide to do. A scorer who knows which image is the thing they built is not
// being dishonest when they rate it higher — they are being human, and the
// instruction to "score fairly" does not survive contact with that.
//
// So the blinding is mechanical. This matches stations across capture sets,
// shuffles each station's images behind neutral letters, writes a scoring
// sheet with the axes already laid out, and puts the mapping in a file the
// scorer is told not to open. `--reveal` prints it and annotates the sheet.
//
// §2.3 does not apply. The shuffle uses real entropy on purpose — a shuffle a
// scorer could predict is not a blind — and nothing generated by the universe
// depends on it. The seed is recorded so the assignment can be re-derived.

import { createHash, randomBytes } from 'node:crypto';
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { copyFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { arg, REPO } from './lib.js';

const CAPS = resolve(REPO, 'docs/captures');
const OUT = join(CAPS, 'blind');
const LETTERS = 'ABCDEFGH';

/** the eight axes, verbatim from §8 — the prompt is half the review */
const AXES = [
  ['Silhouette', 'readable subject at three distances?'],
  ['Light', 'a dominant light with direction AND a secondary bounce or rim? Any surface receiving no light information at all?'],
  ['Depth', 'aerial perspective present? Three separable depth planes?'],
  ['Motion', 'at least one element moving with coherent, non-loopable motion? (unscoreable from a still — say so rather than guessing)'],
  ['Materials', 'every surface nameable without labels?'],
  ['Colour', '≤3 hue families plus one accent; nothing clipping; in vacuum blacks at true 0, in atmosphere no pixel below the lift (§2.8)'],
  ['Chrome', 'delete the HUD entirely and lose no orientation?'],
  ['Honesty', 'does anything on screen contradict the physics the HUD asserts?'],
];

/** the station name inside `NN-tier-name.png`, or null if it does not match */
function station(file) {
  const m = /^\d+-[a-z]+-(.+)\.png$/i.exec(file);
  return m ? m[1] : null;
}

/** deterministic shuffle from a recorded seed — reproducible, unguessable */
function shuffle(list, seed, salt) {
  const keyed = list.map((v, i) => {
    const h = createHash('sha256').update(`${seed}:${salt}:${i}`).digest();
    return { v, k: h.readUInt32BE(0) };
  });
  keyed.sort((a, b) => a.k - b.k);
  return keyed.map((x) => x.v);
}

// --------------------------------------------------------------- reveal ---

if (arg('reveal', false) === true) {
  const keyPath = join(OUT, 'key.json');
  if (!existsSync(keyPath)) {
    console.error('blind: no key.json — nothing to reveal. Run --sets first.');
    process.exit(2);
  }
  const key = JSON.parse(await readFile(keyPath, 'utf8'));
  console.log(`\nblind · sealed ${key.when} · seed ${key.seed}\n`);
  for (const [st, map] of Object.entries(key.stations)) {
    console.log(`  ${st}`);
    for (const [letter, set] of Object.entries(map)) console.log(`    ${letter} → ${set}`);
  }

  const sheetPath = join(OUT, 'SCORE.md');
  if (existsSync(sheetPath)) {
    let sheet = await readFile(sheetPath, 'utf8');
    if (sheet.includes('<!-- revealed -->')) {
      console.log('\nSCORE.md already carries the reveal.');
    } else {
      let block = '\n---\n\n<!-- revealed -->\n## The key\n\n';
      for (const [st, map] of Object.entries(key.stations)) {
        block += `**${st}** — ` + Object.entries(map).map(([l, s]) => `${l} = \`${s}\``).join(' · ') + '\n\n';
      }
      // Whether the sheet was filled in before the reveal is itself evidence,
      // and it is the one thing a reader cannot check afterwards. So record it.
      const filled = !/_\(score 0–5\)_/.test(sheet);
      block += filled
        ? '_Sheet was filled in before the reveal._\n'
        : '> **Warning — the sheet still had empty scores when the key was revealed.**\n'
          + '> This review is not blind. Re-shoot and re-score.\n';
      await writeFile(sheetPath, sheet + block);
      console.log(`\nwrote the key into ${sheetPath}${filled ? '' : '  ⚠ SHEET WAS EMPTY'}`);
    }
  }
  process.exit(0);
}

// ----------------------------------------------------------------- seal ---

const setsArg = String(arg('sets', '') === true ? '' : arg('sets', ''));
if (!setsArg) {
  console.error('blind: --sets RECK-default,RECK-allflags,RECK-reference');
  process.exit(2);
}
const sets = setsArg.split(',').map((s) => s.trim()).filter(Boolean);
if (sets.length < 2) {
  console.error('blind: need at least two sets to have anything to be blind about');
  process.exit(2);
}
for (const s of sets) {
  if (!existsSync(join(CAPS, s))) {
    console.error(`blind: no capture set at docs/captures/${s}`);
    process.exit(2);
  }
}

// group each set's PNGs by station
const byStation = new Map();
for (const s of sets) {
  for (const f of await readdir(join(CAPS, s))) {
    const st = station(f);
    if (!st) continue;
    if (!byStation.has(st)) byStation.set(st, new Map());
    // one image per set per station — the first tier wins, since §8 scores the
    // frame and not the tier
    if (!byStation.get(st).has(s)) byStation.get(st).set(s, f);
  }
}

// A station only scores if every set has it. The reference is one authored
// valley and has no cosmic web, so most stations will drop — that is correct,
// and the surface station is the one §8 actually cares about comparing.
const usable = [...byStation.entries()].filter(([, m]) => m.size === sets.length);
if (!usable.length) {
  console.error('blind: no station appears in every set — nothing comparable to score');
  console.error(`       stations seen: ${[...byStation.keys()].join(', ') || '(none)'}`);
  process.exit(2);
}

await rm(OUT, { recursive: true, force: true });
await mkdir(OUT, { recursive: true });

const seed = randomBytes(8).toString('hex');
const key = { schema: 'aeon-blind/1', when: new Date().toISOString(), seed, sets, stations: {} };

let sheet = '# Blind score — CLAUDE.md §8\n\n'
  + `Sealed ${key.when}. **Do not open \`key.json\`.** Fill every score and every\n`
  + 'sentence first, then `node tools/blind.js --reveal`.\n\n'
  + '§8: score 0–5. **Gate: ≥4 every axis, ≥4.5 mean.** One sentence per axis\n'
  + 'naming the specific pixel region that lost the point. "Looks good" is a\n'
  + 'failed review. So is "not AAA."\n\n';

for (const [st, m] of usable) {
  const dir = join(OUT, st);
  await mkdir(dir, { recursive: true });
  const order = shuffle([...m.keys()], seed, st);
  key.stations[st] = {};
  for (let i = 0; i < order.length; i++) {
    const letter = LETTERS[i];
    key.stations[st][letter] = order[i];
    await copyFile(join(CAPS, order[i], m.get(order[i])), join(dir, `${letter}.png`));
  }
  sheet += `\n---\n\n## ${st}\n\n`;
  sheet += `Images: ${order.map((_, i) => `\`${st}/${LETTERS[i]}.png\``).join(' · ')}\n\n`;
  for (let i = 0; i < order.length; i++) {
    const L = LETTERS[i];
    sheet += `### ${L}\n\n`;
    sheet += '| axis | score | the pixel region that lost the point |\n|---|---|---|\n';
    for (const [name, ask] of AXES) {
      sheet += `| **${name}** — ${ask} | _(score 0–5)_ |  |\n`;
    }
    sheet += '\n**Mean:** ·  **Verdict:** \n\n';
  }
}

await writeFile(join(OUT, 'key.json'), JSON.stringify(key, null, 2) + '\n');
await writeFile(join(OUT, 'SCORE.md'), sheet);

console.log(`\nblind · ${usable.length} station(s) × ${sets.length} sets → docs/captures/blind/`);
for (const [st] of usable) console.log(`   ${st}/  ${sets.map((_, i) => LETTERS[i] + '.png').join(' ')}`);
console.log(`\n   fill in  docs/captures/blind/SCORE.md`);
console.log(`   then     node tools/blind.js --reveal`);
console.log(`\n   do not open key.json first — a blind test you peeked at is an`);
console.log(`   unblinded test with extra steps.\n`);
